pnp/pnpframework

src/lib/PnP.Framework/Modernization/Delve/DelvePageTransformator.cs, src/lib/PnP.Framework/Modernization/Extensions/ListItemExtensions.cs, src/lib/PnP.Framework/Modernization/Extensions/SiteExtensionsModernization.cs, src/lib/PnP.Framework/Modernization/KQL/KQLParser.cs, src/lib/PnP.Framework/Modernization/Pages/BasePage.cs, src/lib/PnP.Framework/Modernization/Publishing/PublishingPageTransformator.cs, src/lib/PnP.Framework/Modernization/Transform/BasePageTransformator.cs, src/lib/PnP.Framework/Modernization/Transform/BaseTransform.cs, src/lib/PnP.Framework/Modernization/Transform/ContentByQuerySearchTransformator.cs, src/lib/PnP.Framework/Modernization/Transform/PageTransformator.cs, src/lib/PnP.Framework/Modernization/Transform/TermTransformator.cs, src/lib/PnP.Framework/Modernization/Utilities/CookieManager.cs
Fix some warnings, mostly about unused variables
=> Fix some warnings

src/lib/PnP.Framework/Extensions/PageExtensions.cs, src/lib/PnP.Framework/Extensions/TenantExtensions.cs, src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, src/lib/PnP.Framework/Provisioning/Providers/Xml/Resolvers/V202002/SharingSettingsFromSchemaToModel.cs
Porting PRs from sites core repository. 
Tested and checked. 
We can also merge the PRs in sites core.
List of PRs:
1) https://github.com/pnp/PnP-Sites-Core/pull/2790
2) https://github.com/pnp/PnP-Sites-Core/pull/2784
3) https://github.com/pnp/PnP-Sites-Core/pull/2775
4) https://github.com/pnp/PnP-Sites-Core/pull/2762
5) https://github.com/pnp/PnP-Sites-Core/pull/2760
=> Porting PR from sites core

src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs
Hi, I noticed a NullReferenceException when i added a Webhook Subscription and fixed it.
Kind Regards
Martin
=> Fixed NullReferenceException when adding Webhook Subscription

src/lib/PnP.Framework/Extensions/PageExtensions.cs, src/lib/PnP.Framework/Modernization/Telemetry/PageTelemetry.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs
This PR 
1) Removes some extra checks for checking server version in publishing pages since we will always be in SPO
2) Removes check for ZoneId property as well since we will always be in SPO 
3) Fixed the deprecated method for telemetry tracking, not sure if it fixes the DLL hell issue but worth a check :)
=> Improvements - removed some extra checks + maybe telemetry fix

src/lib/PnP.Framework/Extensions/BrandingExtensions.cs, src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs, src/lib/PnP.Framework/Extensions/PageExtensions.cs, src/lib/PnP.Framework/Extensions/PublishingExtensions.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectFiles.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs
Using `GetFileByServerRelativePath` and `GetFolderByServerRelativePath` where possible.
=> Feature - Additional underlying changes to API

src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenParser.cs
Fix for unhandled null reference exception if you did not specify a hierarchy or template file connector when provisioning a template with localization files.
=> Fix for unhandled null reference exception

src/lib/PnP.Framework/Sites/SiteCollection.cs, src/lib/PnP.Framework/Sites/SiteCollectionCreationInformation.cs
Feature - added HubSiteId, SensitivityLabel and SiteDesignId properties for Team sites without M365 groups.
=> Feature - added additional props for Team Site No Group

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenParser.cs
1) Improved Modern site retrieval 
2) Upgraded to v1 teams endpoint for Teams template provisioning
3) Potentially fixing #51 by catching the exception and not stopping provisioning in case of Graph error
=> Feature - minor improvements related to Graph

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs
Potentially fixes - https://github.com/pnp/powershell/issues/43
In case of App-only mode, will use the Graph endpoint to create the team.
=> Fix - app-only issue for teamifying group sites

src/lib/PnP.Framework/Graph/PnPHttpProvider.cs, src/lib/PnP.Framework/Utilities/PnPHttpProvider.cs, src/lib/PnP.Framework/Utilities/PnPHttpRetryHandler.cs
HTTP exceptions were thrown as AggregateExceptions
Fixed and refactored HTTP retry mechanisms
=> Fix http exception unwrapping, refactor http retry mechanism

src/lib/PnP.Framework/AuthenticationManager.cs, src/lib/PnP.Framework/Utilities/ACSTokenGenerator.cs, src/lib/PnP.Framework/Utilities/TokenHelper.cs, src/lib/PnP.Framework/Utilities/TokenHelperOptions.cs
Alright, so this is my proposal on how to handle token generation in the feature. I tried to untangle the ACS token generation bit, moved it to a separate namespace.
- Refactor ACS token creation
- Add geneirc support for OAuthAuthenticationProvider
- Implement OAuthAuthenticationProvider for ACS token generation
- Make ACS token generation thread-safe
=> Refactor ACS token creation

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteFooterSettings.cs
Fix PnP PowerShell issue - https://github.com/pnp/powershell/issues/211
=> Fix #211 - initialize serverrelative path for site footer

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs
Fix since RegEx.Escape in ListContentTypeIdToken.CreateToken does escape whiteSpace with \ it breaks the JSON in NewDocumentTemplates
=> Fix Escaped whiteSpace break JSON in NewDocumentTemplates

.vscode/tasks.json
Adding build profile to allow for easier ctrl+alt+b to build the PnP Framework
=> Adding build profile

src/lib/PnP.Framework/Http/PnPHttpClient.cs
Bring back ability to take UserAgent from config or environment when use new HttpClient Factory
=> Allow to have Custom UserAgent when use PnPHttpClient.Instance.GetHttpClient

src/lib/PnP.Framework/Provisioning/Providers/Xml/readme.md
Namespace was still the old namespace. Updated it to reflect the namespace currently being used.
=> Updated namespace to be the proper value

docs/MigratingFromPnPSitesCore.md
Hi 
I made a change to the Migration instructions document to reflect renaming of Initialize-PnPPowerShellAuthentication to Register-PnPAzureADApp and the new different parameters
Thanks
=> Documentation updates

src/lib/PnP.Framework/Sites/SiteCollection.cs
Fix a typo in the comments, "intered" -> "interested"
=> Fix a typo in the comments

src/lib/PnP.Framework/Extensions/TenantExtensions.cs
Fixes  - https://github.com/pnp/powershell/issues/544.
Adds ability to set Security/M365 groups as owners of site collections.
=> Fix #544 - add groups as owners of site collections

src/lib/PnP.Framework/Provisioning/BaseTemplates/SPO/TEAMCHANNEL0Template.xml, src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/SiteCollectionConnectedOffice365GroupId.cs
Adding the TEAMCHANNEL0 Template as XML and use RelatedGroupId as fallback for the {sitecollectionconnectedoffice365groupid} token during provisioning
=> Minimal support for TEAMCHANNEL Template

src/lib/PnP.Framework.Test/Utilities/UnifiedGroupsUtilityTests.cs, src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs
Fix #271: Added Preferred Data Location support for creating sites via PnP PowerShell and Graph token
=> Fix #271: Added PDL support for creating sites via PnP PowerShell

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs, src/lib/PnP.Framework/Utilities/UrlUtility.cs
Improve alias naming for modern sites by removing special and accented characters.
=> Feature: improve alias naming for modern sites.

src/lib/PnP.Framework/AuthenticationManager.cs
Fix #275 - for tenantId missing issue
=> Fix #275 - for tenantId missing issue

src/lib/PnP.Framework/AuthenticationManager.cs
Fix #275 - implement a better fix compared to previous PR !
=> Fix #275 - implement a better fix compared to previous PR !

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
#338 - added HostUrl token for Hubsite url property
=> Feature #338 - added HostUrl token for Hubsite url property

src/lib/PnP.Framework/Utilities/PnPCoreUtilities.cs
Adding operating system to user agent string sent along with every PnP request, also to the microsoftonline authentication endpoints in order to fix issue https://github.com/pnp/powershell/issues/737.
=> Adding operating system in order to fix issue #737

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs
Fix issue  - https://github.com/pnp/powershell/issues/1024
Adds support to create folder name with special chars.
=> Fix PnPPS #1024 - issue with folder name having special chars

src/lib/PnP.Framework/Extensions/TenantExtensions.cs
Fix a regression due to an earlier change while adding users/M365 groups as site collection admins.
This one does a proper fix to ensure that users and M365 groups both can be added as site collection admins and part of owners group.
=> Fix regression - adding users/groups as site collection admins

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs, src/lib/PnP.Framework/Utilities/UrlUtility.cs
Additional changes for folders and files which contain special characters.
=> Feature - additional changes for files/folders with special chars

src/lib/PnP.Framework/Graph/UsersUtility.cs
Fixing issue where requesting a selectProperties which would already be part of the default mapped properties would cause an exception
=> UsersUtility selectProperties bugfix

src/lib/PnP.Framework.Test/Resources/Templates/ProvisioningTemplate-2019-03-Sample-01-test.xml, src/lib/PnP.Framework.Test/Resources/Templates/ProvisioningTemplate-2019-09-Sample-01-test.xml, src/lib/PnP.Framework.Test/Resources/Templates/ProvisioningTemplate-2020-02-Sample-01-test.xml, src/lib/PnP.Framework.Test/Resources/Templates/ProvisioningTemplate-2021-03-Sample-01-test.xml, src/lib/PnP.Framework/Extensions/SecureStringExtensions.cs, src/lib/PnP.Framework/Provisioning/Model/ALM/ApplicationLifecycleManagement.cs, src/lib/PnP.Framework/Provisioning/Model/AzureActiveDirectory/PasswordProfile.cs, src/lib/PnP.Framework/Provisioning/Model/AzureActiveDirectory/User.cs, src/lib/PnP.Framework/Provisioning/Model/Hierarchy/ProvisioningSequence.cs, src/lib/PnP.Framework/Provisioning/Model/ProvisioningTemplate.cs, src/lib/PnP.Framework/Provisioning/Model/SharePoint/InformationArchitecture/ContentType.cs, src/lib/PnP.Framework/Provisioning/Model/SharePoint/Navigation/BaseNavigationKind.cs, src/lib/PnP.Framework/Provisioning/Model/SharePoint/Publishing/Publishing.cs, src/lib/PnP.Framework/Provisioning/Model/Teams/Team.cs, src/lib/PnP.Framework/Provisioning/Model/Teams/TeamTab.cs, src/lib/PnP.Framework/Provisioning/Model/TenantSettings/ContentDeliveryNetwork.cs, src/lib/PnP.Framework/Provisioning/Model/TenantSettings/ProvisioningTenant.cs
- Fix equality comparisons in Provisioning model objects
- Added a method extension to compare SecureStrings
- Fixed access to nullable `SharingSettings` property
=> Fix equality comparisons in Provisioning model objects

src/lib/PnP.Framework/PnP.Framework.csproj
Fix issue #547  with trace log entries being empty when using PnP PowerShell
Credit to @ygrenier for the investigation !!
=> Fix #547 - issue with trace log

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs
When adding a data row with a field as "Geolocation" is not setting the item to the list
=> Added missing field Type "Geolocation" case in UpdateListItem()

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
Exporting Teams channels, checking membershipType to check if Channel is private and set the Private property to true.
=> Setting Teams channel as private according to membershipType

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectExtensibilityHandlers.cs
Added progress logging for provisioning of extensibility handlers
=> Added progress logging for provisioning of extensibility handlers

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs
Fix for unauthorized exception in EnsureFolder when user is not a site owner.
=> Fix for unauthorized exception in EnsureFolder

src/lib/PnP.Framework/Sites/SiteCollection.cs
Feature : remove special chars from the SiteAlias property while creating a modern site collections
=> Feature : remove special chars from the SiteAlias

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs
Fix: for adding folders in large lists/doc libs and overcoming threshold issues
=> Fix: for adding folders in large list

src/lib/PnP.Framework/Graph/Model/TemporaryAccessPassRequest.cs, src/lib/PnP.Framework/Graph/Model/TemporaryAccessPassResponse.cs, src/lib/PnP.Framework/Graph/UsersUtility.cs
Added the [ability to request temporary access passes](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-temporary-access-pass) for Azure Active Directory users
=> Added RequestTemporaryAccessPass method to UsersUtility

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/TermGroupHelper.cs
Fix an exception happening when exporting a PnP template with `Get-PnPSiteTemplate -IncludeSiteCollectionTermGroup -Handlers TermGroups` and applying it to another tenant. The Owner field of `<pnp:Term Owner="...">` would point to the owner of the source tenant, which cannot be found on the destination tenant.
This PR adds a "user exists" check and logs a warning when the user is not found.
This is the error happening without this PR:
I couldn't find a generic "DoesUserExist()" method in the library, please let me know if I missed it and if I should update the PR
=> Fix exception thrown when a Taxonomy Term owner was not found

src/lib/PnP.Framework/Extensions/PageExtensions.cs, src/lib/PnP.Framework/PnPCoreSdk.cs
Some PnP SDK interop methods are not async and blocking under the hood, which can be improved, since ideally we in our application codebase we should [use async all the way down](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).  
This PR adds async methods for `PageExtensions`: 
- `LoadClientSidePageAsync` 
- `AddClientSidePageAsync`
For `PnPCoreSdk`:
- `GetPnPContextAsync`
- `GetClientContextAsync`
=> Added async counterparts for PnP SDK interop.

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs
This quick fix for https://github.com/pnp/pnpframework/issues/646 until https://github.com/pnp/pnpframework/pull/567 is finished.
=> Implement show / hide of site title in header using SetChromeOptions

src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs
When developers use proxy validations by user agents, this change will add the user agent used on app configuration or use the PnP default User-Agent.
=> Add UserAgent to ExecuteQuery

src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs
Fixes: https://github.com/pnp/powershell/issues/1696
Use Graph token if possible instead of the the unsupported teams creation methods
=> Fix #1696 - issue with team creation , use graph token if possible

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs
Added an optional parmeter to prevent sending of default welcome emails to new members.
=> Add optional parameter to disable welcome message

src/lib/CHANGELOG.md, src/lib/PnP.Framework.Test/Framework/ObjectHandlers/ObjectSiteSettingsTests.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteSettings.cs
=> Added ShowPeoplePickerSuggestionsForGuestUsers Schema Implementation

src/lib/PnP.Framework.Test/Framework/ObjectHandlers/ObjectListInstanceTests.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Audience targeting for classic/modern
Tests
=> Audience Targeting

src/lib/CHANGELOG.md
=> Change Log Update

src/lib/PnP.Framework.Test/Framework/ObjectHandlers/ObjectTeamsTests.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
- Added Extraction of settings
- Added Provisioning of Settings
- Added tests
=> Teams Moderator Settings

src/lib/PnP.Framework/Constants.cs, src/lib/PnP.Framework/Extensions/ListExtensions.cs, src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
- Moved bulk of method to List Extensions
- Will support use of operation in PnP PowerShell in future
- Tested with existing tests
=> Improvement to audience targeting

src/lib/PnP.Framework/Enums/Office365Geography.cs
Added a few geo locations that has been recently added by Microsoft.
=> Add geo locations that has been recently added

src/lib/PnP.Framework/Extensions/ListExtensions.cs
| Related issues?  | #772 
This PR makes sure that the LookupMulti field for ModernAudienceTargeting is using User Information List in the correct way. It also adds the two Event Receivers that is added by the out of the box feature.
=> Fixes for the EnableModernAudienceTargeting method

src/lib/PnP.Framework/Utilities/MailUtility.cs
Fixing memory leaks and adding ability to authenticate to SMTP with a specific username which differs from the from address for i.e. shared mailboxes
=> Updates to MailUtility

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs
Fix: https://github.com/pnp/powershell/issues/2831
Added additional optional parameter to support different Azure env for site creation
=> Feature #2831: support for different azure environment for team site creation

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs, src/lib/PnP.Framework/Sites/SiteCollection.cs
Fix - https://github.com/pnp/powershell/issues/2948
=> Fix Azure environment issue for non-commercial clouds in create team site

src/lib/PnP.Framework/Graph/UsersUtility.cs
Fix for https://github.com/pnp/powershell/issues/3478
=> Feature: Added GCC support for users utility

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Fixes two errors introduced by my previous fix in #915.
=> fix(provisioning): occasional crash when setting default values

src/lib/PnP.Framework/Provisioning/Providers/Markdown/Writers/TemplateListInstancesWriter.cs
Added list fields to Markdown output for list instances in PnP site template conversion
=> Improved list information in template MD conversion

src/lib/PnP.Framework/PnP.Framework.csproj
=> Update Microsoft.Identity.Client.Extensions.Msal to version 4.60.3

src/lib/PnP.Framework/PnP.Framework.csproj
chore: update Microsoft.Identity.Client.Extensions.Msal to version 4.61.1
=> chore: update Microsoft.Identity.Client.Extensions.Msal to version 4.61.1

src/lib/PnP.Framework/AuthenticationManager.cs
Fixes https://github.com/pnp/powershell/issues/3206
=> Feature: improve managed identity token acquisition support to default built-in MSAL methods.

src/lib/PnP.Framework/PnP.Framework.csproj
Bump MSAL.NET to latest for security fixes
=> Bump MSAL.NET to latest for security fixes

src/lib/PnP.Framework/Extensions/ListExtensions.cs
Fix https://github.com/pnp/powershell/issues/3783 : issue with audience targeting in modern lists
=> Fix #3783 : issue with audience targeting in modern lists

src/lib/PnP.Framework/AuthenticationManager.cs
=> Fixed typo

src/lib/PnP.Framework/AuthenticationManager.cs
Fix: Improve perf for managed identity auth
=> Fix: Improve perf for managed identity auth
