src/lib/PnP.Framework/Provisioning/Extensibility/ExtensibilityManager.cs

Fix for instantiating extensibility handlers.
The previous code assumed that the extensibility handler assembly was located in the same folder as the executing assembly and that the handler assembly name specified in the HandlerType attribute for the Provider in the provisioning template was in its short form. If it was specified as a fully qualified name it would look for a file named something like "TestExtensibilityHandler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.xml". We would also not be able to load extensibility handlers from somewhere else than the same folder as the executing assembly.
With this fix handlers located in the same …

Fix for instantiation of extensibility handlers

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fixes some issues relating to token parsing when provisioning folders:
- Tokens was not parsed in folder default value field names and values
- Tokens was not parsed in folder property field name
- Tokens was not parsed in folder property bag key
- Sub-folders were created before the parent folder default values had been provisioned and because of this never received the default field values
Original PR for PnP-Sites-Core [https://github.com/pnp/PnP-Sites-Core/pull/2765](https://github.com/pnp/PnP-Sites-Core/pull/2765)

Fix for token parsing when provisioning folders

---

src/lib/PnP.Framework/Modernization/Cache/CacheManager.cs
src/lib/PnP.Framework/Modernization/Caml/FieldReference.cs
src/lib/PnP.Framework/Modernization/Caml/ListPropertyValueItem.cs
src/lib/PnP.Framework/Modernization/Extensions/StringExtensions.cs
src/lib/PnP.Framework/Modernization/Functions/BuiltIn.cs
src/lib/PnP.Framework/Modernization/Publishing/PageLayoutAnalyser.cs
src/lib/PnP.Framework/Modernization/Publishing/PublishingBuiltIn.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/ConsoleObserver.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/MarkdownObserver.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/MarkdownToSharePoint.cs
src/lib/PnP.Framework/Modernization/Transform/AssetTransfer.cs
src/lib/PnP.Framework/Modernization/Transform/BasePageTransformator.cs
src/lib/PnP.Framework/Modernization/Transform/BaseTransform.cs
src/lib/PnP.Framework/Modernization/Transform/ContentByQuerySearchTransformator.cs
src/lib/PnP.Framework/Modernization/Transform/TermTransformator.cs
src/lib/PnP.Framework/Modernization/Transform/UserTransformator.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenParser.cs
src/lib/PnP.Framework/Utilities/TokenHelper.cs

Fixes the following warnings related to XML comments:
- CS1572 "XML comment on 'construct' has a param tag for 'parameter', but there is no parameter by that name" https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1572
- CS1587 "XML comment is not placed on a valid language element" https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1587
- CS1570 "XML comment on 'construct' has badly formed XML — 'reason'" https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1570
On top of these there are a lot of warnings about parameters missing in the XML comments. Is there any meaning in adding those without any actual comment in another PR or is it better to keep the warnings as reminder ?

Fix some warnings related to XML comments

---

src/lib/PnP.Framework.Test/Utilities/UrlUtilityTests.cs
src/lib/PnP.Framework/Extensions/ListExtensions.cs
src/lib/PnP.Framework/Utilities/UrlUtility.cs

SharePoint is expecting a specific type of URL Encoding for href values in client_LocationBasedDefaults.html (the file which SharePoint produces to store the "Column default settings" for a document library) as can be observed when inspecting the file in the /Forms directory for the library after configuring defaults through the SharePoint UI. The type of encoding used by SharePoint leaves slashes alone and replaces spaces with %20 rather than '+' signs.
This PR addresses a bug in pnp framework (inside the SetDefaultColumnValuesImplementation method) where System.Web.HttpUtility.UrlEncode(path) is used to encode href values, which does not result in the type of encoding expected by SharePoint.

fix url encoding issue when writing href values to client_LocationBasedDefaults.html as part of SetDefaultColumnValuesImplementation()

---

src/lib/PnP.Framework.Test/Extensions/TaxonomyExtensionsTests.cs
src/lib/PnP.Framework/Extensions/TaxonomyExtensions.cs

This is a copy of pull request [2776](https://github.com/pnp/PnP-Sites-Core/pull/2776) in the original PnP-Sites-Core repository.
| Related issues?  | fixes [1955 (on PnP-Sites-Core)](https://github.com/pnp/PnP-Sites-Core/issues/1955)
Fixes an issue where importing terms which include commas, while also providing a GUID for the terms, would create the wrong hierarchy in the termstore.
A import like this:
> Group;#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX|Set;#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX|"TermX,TermY";#ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
would create a structure like this
> Group > Set > "TermX > TermY"
> TermY" has the GUID ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
instead …

Fix issue with handling of terms with comma and provided GUID

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/Enums/TimeZone.cs
src/lib/PnP.Framework/Modernization/Cache/CacheManager.cs
src/lib/PnP.Framework/Modernization/Extensions/ListItemExtensions.cs
src/lib/PnP.Framework/Modernization/Functions/BuiltIn.cs
src/lib/PnP.Framework/Modernization/Functions/FunctionProcessor.cs
src/lib/PnP.Framework/Modernization/Pages/BasePage.cs
src/lib/PnP.Framework/Modernization/Pages/PublishingPage.cs
src/lib/PnP.Framework/Modernization/Pages/PublishingPageOnPremises.cs
src/lib/PnP.Framework/Modernization/Publishing/PublishingBuiltIn.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/ConsoleObserver.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/MarkdownObserver.cs
src/lib/PnP.Framework/Modernization/Telemetry/Observers/MarkdownToSharePoint.cs
src/lib/PnP.Framework/Modernization/Transform/AssetTransfer.cs
src/lib/PnP.Framework/Modernization/Transform/BaseTransform.cs
src/lib/PnP.Framework/Modernization/Transform/TermTransformator.cs
src/lib/PnP.Framework/Modernization/Transform/WikiHtmlTransformator.cs
src/lib/PnP.Framework/Pages/CanvasColumn.cs
src/lib/PnP.Framework/Utilities/PnPCoreUtilities.cs

This PR add some missing XML comments and fixes some typos found while going through the comments.
As there are 2400 warnings, I started with [CS1573](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573) ones, so methods already with XML comments but with some parameters missing.
I tried to check how the same parameters/properties were commented in the existing code to keep them similar and give a better user experience, i.e. contructor parameter and public property having the same comment.
In some cases I checked how the methods are used or ```git blame``` to get a better understanding of what each parameter does.
I might keep pushing new commits to this PR but feel free to merge it whenever you want 😃

Add some missing XML comments

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/Utilities/Context/ClientContextType.cs

Q | A
-- | --
Bug fix? | no
New feature? | yes
New sample? | no
Related issues? | #13
**What is in this Pull Request?** 
The pull request is made as a consequence of  issue #13. The PR contains the code to facilitate retrieval of client context by using Enterprise Application (`clientid,clientsected`) with granted admin consent to acquire tokens on behalf of the user (`userAssertion`).
The added constructor uses `(string clientId, string clientSecret, UserAssertion userAssertion,...)` as parameters. At first the `UserAssertion ` was attempted to be used as `string token` parameter which is then constructed into `UserAssertion`.  It did not work, because there already are constructors using 3-4 string parameters. Therefore `Microsoft.Identity.Client.UserAssertion `is explicitly used.
The …

Added Azure OnBehalfOf token acquiring

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Currently, we can only extract 100 teams, if there are more than 100 teams then it won't work. This PR adds support for extracting >100 teams via the provisioning engine.
Please let me know if I should port it back to PnP Sites core as well.

Feature: Added support to extract all teams

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Just replaces a graph beta call to remove a teams tab with a call to the already existing method that uses a v1 graph call

Replaced graph beta call with already existing private method with v1 graph call

---

src/lib/PnP.Framework/Sites/SiteCollection.cs
src/lib/PnP.Framework/Sites/SiteCollectionCreationInformation.cs

Adds the ability to specify the SiteAlias during team site collection creation, i.e. the site segment of the url, e.g. https://contoso.sharepoint.com/sites/ &lt;SiteAlias&gt;

Added SiteAlias to Site Collection creation

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

Make sure the Overwrite attribute is honoured when deploying packages through a Tenant template

Bug fix - Honour Overwrite attribute on Package in Tenant template

---

src/lib/PnP.Framework/Provisioning/Connectors/SharePointConnector.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectPages.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteFooterSettings.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs

Replaced the GetFileByServerRelativeUrl to GetFileByServerRelativePath methods in the provisioning engine to support special chars in file names

Feature - replaced GetFileByServerRelativeUrl to GetFileByServerRelativePath method

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs

- Fix ACS access token generation  #34 
- Add null pointer check
- Fall back to template LCID for ClientSitePage if none is provided

Fix ACS token generation

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

Looks like during some merge , we missed the Sensitivity Label and Preferred data location changes. 
This PR fixes that.

Fix - sensitivity label + preferred data location missing changes

---

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs

Updated Graph beta endpoints to v1.0 for UnifiedGroups methods - PermanentDeleteGroup, RestoreGroup and GetDeletedGroup

Feature - update beta endpoints to v1.0 for UnifiedGroups methods

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs

The parsing already happens, but the result isn't used. This PR seeks to fix that.

Parse tokens in the SearchCenterUrl

---

src/lib/PnP.Framework/AuthenticationManager.cs

Code should check the return value of `certfile.Read(certificateBytes, 0, (int)certfile.Length)` because it may read less than `certfile.Length` bytes. This patch delegates the work to X509Certificate2. A good alternative would be to use `System.IO.File.ReadAllBytes(certificatePath)`.
I also think that disposing the certificate here is not correct. Isn't the disposed certificate later used by ConfidentialClientApplication?

fix reading certificate bytes

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

Keep the existing stack information on rethrowing the exception. Makes more sense for debugging.

Keep the existing stack information on rethrowing the exception.

---

src/lib/PnP.Framework/PnPCoreSdkAuthenticationProvider.cs

Fix a null reference exception in cases where ClientContextSettings are null. Fixes #70

Fix a null reference exception in cases where ClientContextSettings are null.

---

src/lib/PnP.Framework/Extensions/FieldAndContentTypeExtensions.cs

Ported PR from PnP Sites Core - https://github.com/pnp/PnP-Sites-Core/pull/2582 
Please credit him for this implementation. 
Checked it, works as expected

Feature - improved best match implementation of content type id

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Added token parsing of team displayname in log message which would otherwise cause an exception if the displayname contained a token.

Added token parsing of team displayname in log message

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Added check for existing team before checking archived status so that we don't get an error logged for every new site collection with team being provisioned. Since the check for isArchived will cast an exception if the group doesn't exist this would always be cast when provisioning a new site collection with a team using a tenant template and by first checking if the team exists the isArchived check can be skipped.

Added check for existing team before checking archived status

---

src/lib/PnP.Framework/Extensions/FieldAndContentTypeExtensions.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

Allow bool Flags to be null for AddFieldToContentType and pass null for ReadOnly and ShowInDisplayForm if called from ObjectContentTypes as template schema does not support this 2 settings and we should use the settings from sitecolumn.

fix wrong ReadOnly setting on ContentType LinkedFields 

---

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs

Hi,
I'm trying to update a unified group with an existing user or owner, the Graph request is giving an error...
```
POST https://graph.microsoft.com/v1.0/groups/5d08888a-d9e3-44e9-8371-46f4d774ed72/owners/$ref HTTP/1.1
Host: graph.microsoft.com
User-Agent: NONISV|SharePointPnP|PnPCore/1.1.0.0
...
{"@odata.id":"https://graph.microsoft.com/v1.0/directoryObjects/56bc8f87-b25e-463d-88ef-1a243acccebd"}
```
and the response...
```
HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
...
{
"error": {
"code": "Request_BadRequest",
"message": "One or more added object references already exist for the following modified properties: 'owners'.",
"innerError": {
"date": "2021-01-27T18:01:47",
"request-id": "1064c860-10b6-4c37-827b-00196731c901",
"client-request-id": …
```

Fix bug when trying to add existing member or owner to a unified group.

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs

Minor changes on ObjectHandler/ObjectClientSidePages.cs to allow use of tokens for the page properties TopicHeader and AlternativeText.
<pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="false" Overwrite="true" EnableComments="false" Title="{resource:ListingMixedCommunicationsTitle}" ContentTypeID="0x0101...." PageName="test.aspx">
<pnp:Header Type="Custom" LayoutType="NoImage" ShowTopicHeader="true" ShowPublishDate="false" TextAlignment="Center" **TopicHeader="{resource:ListingTitle}" AlternativeText="{resource:ListingTestTitle}"** Authors="[]" AuthorByLine="[]" AuthorByLineId="-1" />
<pnp:Sections>
<pnp:Section Order="1" Type="ThreeColumn">
...

Allow use of tokens for TopicHeader and AlternativeText in Pages

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

PR for fixing issue #142 
Instead of adding the key-value, It updates the value for key WebTemplateExtensionId in the payload dictionary.

Updating WebTemplateExtensionId value in payload dictionary.

---

src/lib/PnP.Framework/Provisioning/Connectors/OpenXML/PnPPackage.cs
src/lib/PnP.Framework/Provisioning/Connectors/OpenXML/PnPPackageFormatException.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
src/lib/PnP.Framework/Provisioning/Providers/Markdown/MarkdownPnPSchemaBaseWriter.cs
src/lib/PnP.Framework/Utilities/OAuth/DateTimeUtil.cs
src/lib/PnP.Framework/Utilities/Themes/Palettes/Shades.cs
src/lib/PnP.Framework/Utilities/UnitTests/Web/MockEntryResponseProvider.cs

- CA1032: Implement standard exception constructors
- CA1507: Use nameof in place of string
- CA1834: Use StringBuilder.Append(char) for single character string
- CA1802: Use Literals Where Appropriate
- CA1825: Avoid zero-length array allocations

Fix some warnings

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

fix because Modern List Creation (Lists-Dialog) creates CTType with 0x01[Parent1][Parent2] but Parent1 does not exist so it's not resolved above and we try to create the builtin CT 0x01 found by export and fail to create

fix because Modern List Creation creates CTType with 0x01[Parent1][Parent2] but Parent1 does not exist

---

src/lib/PnP.Framework/Graph/UsersUtility.cs

Fixed bug in endIndex not being applied correctly, made endIndex nullable to allow for retrieval of all available results. Used by PnP PowerShell through [PR #223](https://github.com/pnp/powershell/pull/223).

Updated UsersUtility

---

src/lib/PnP.Framework/ALM/AppManager.cs
src/lib/PnP.Framework/Extensions/FeatureExtensions.cs
src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs
src/lib/PnP.Framework/Sites/SiteCollection.cs

Replace Thread.Sleep() with Task.Delay() in async methods as Thread.Sleep() suspends the current thread that, in case of async methods, could be a thread-pool thread, not allowing it to process other tasks.

Replace Thread.Sleep() with Task.Delay() in async methods

---

src/lib/PnP.Framework/Entities/UnifiedGroupUser.cs
src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs

We were already retrieving the full Graph user details anyway, but were not converting these over from the Graph `User` object to the PnP Framework `UnifiedGroupUser` equivalent. Updated the `UnifiedGroupUser` object to expose these properties we already have anyway. Doesn't require any additional calls to be made and the existing two properties remain unchanged, so this is backwards compatible.

Added additional Graph User properties

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Fix for checking the teams tab app id. The old teamsappid property way only exists in the beta endpoint and nowadays seems to return null for some (if not all) apps. The way it is done in this PR is the way the documentation says is the way to do it.

Fix: Changed the way we check the teams tab app id

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Fix for updating a team if a tab had Remove = True in the template. Without this fix the update aborted when it ran into a tab that had Remove = True.

Fix for updating team if a tab had Remove = True

---

src/lib/PnP.Framework/Extensions/TenantExtensions.cs

Improved Tenant Id fetch method for non-Production use tenants.
Currently this method only works for standard M365 tenants, extended it to work with other M365 environments as well.

Feature - Improved Tenant Id fetch method

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectFiles.cs

Upload of template files to the Forms folder of the Library did fail because of access to targetFile.ListItemAllFields.Id -
Added Check if have ListItemAllFields.

fix if file is template in /libname/Forms folder and therefore has no ListItemId

---

src/lib/PnP.Framework/Extensions/SiteExtensions.cs

Added methods to return and register an event receiver at the site collection level (similar to web level).
```
GetEventReceiverById
GetEventReceiverByName
AddRemoteEventReceiver
```
It would resolve https://github.com/pnp/powershell/issues/241

Added Get/Add EventReceiver method to SiteExtensions

---

src/lib/PnP.Framework/Modernization/Extensions/ListItemExtensions.cs

Fix for ListItem.GetFieldValueAs which did not work for all field types, e.g. FieldUserValue and TaxonomyFieldValue.

Fix for ListItem.GetFieldValueAs not working for other types than string

---

src/lib/PnP.Framework/Sites/SiteCollection.cs
src/lib/PnP.Framework/Sites/SiteCollectionCreationInformation.cs

Allow to specify the Sensitivity Label Id when creating a new site collection, in addition to the Display name already supported. If both Id and Display name are specified, no exception is thrown but the Id takes precedence.
This is needed in a real-world case in a provisioning solution using Azure Functions where the sensitivity label is passed from another system as guid.

Allow to specify the Sensitivity Label Id when creating a new site collection

---

src/lib/PnP.Framework/ALM/AppManager.cs

Fix AudienceUriValidationFailedException exceptions when using AppCatalogScope.Tenant scope but not being connected to the AppCatalog due to using the original Context instead of the AppCatalog cloned one.
The issue has been added in https://github.com/pnp/pnpframework/commit/7ccbab82ea10ba98ebb48b8899d2b6cce47addb4 most likely as a common copy&paste typo as "context" and "_context" are very similar.
This PR fixes for example calling
```powershell
Add-PnPApp -Path $Package -Overwrite -Scope Tenant -Connection $Connection
```
with a connection pointing to the Admin portal. Without this PR a AudienceUriValidationFailedException is thrown as the token used points to a different url than the AppCatalog.

Fix AudienceUriValidationFailedException exceptions when using AppCatalogScope.Tenant

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

When using the provisioning engine to create a site design, the WebTemplate property was not being set, and therefore was not showing up in the select a topic UI when creating a new site.
The reason for this was the WebTemplate property (which is a SiteDesignWebTemplate enum with the options TeamSite = 64 and CommunicationSite = 68) was expecting a 0 and 1 instead of 64 or 68 respectively.
This PR corrects this for both new site designs as well as updating existing (when the Overwrite property is true) site designs via the provisioning engine.

Fix Site Design creation/update via provisioning engine - WebTemplate not being set

---

src/lib/PnP.Framework/Provisioning/Providers/Xml/Serializers/V201705/ListInstancesSerializer.cs
src/lib/PnP.Framework/Provisioning/Providers/Xml/Serializers/V201909/ListInstancesSerializer.cs

The UserCustomAction on Lists could not be provisionied when needing ClientSideComponentId as it was not loaded by the Deserializer. As the Field did already exist in 2017, added the statement to both ListInstanceSerializer.cs (201705 / 201909)

Deserialze of Template XML does not load ClientSideComponentId on List-UserCustomAction

---

src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs

Fix so that WebRequestExecutorFactory is copied when cloning context between different audiences.

Fix to always copy WebRequestExecutorFactory when cloning

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Implemented some retry logic for getting and creating teams tabs. Sometimes an exception is thrown when getting or creating teams tabs immediately after creating teams channels, especially when creating multiple private channels and under higher load so this fix checks for that and retries the operation.

Fix: Implemented retry logic for getting and creating teams tabs

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Fix so that a teams private channels always are created with isFavoriteByDefault=false since a private channel cannot be created with isFavoriteByDefault=true. When trying to an error will be returned from Graph and the provisioning process is interrupted without any message on what went wrong.

Fix: Always create private channels with isFavoriteByDefault false

---

src/lib/PnP.Framework/Http/HttpClientWebRequestExecutorFactory.cs

Added an implementation of WebRequestExecutorFactory and SPWebRequestExecutor that utilizes HttpClient instead of HttpWebRequest.  
This has the following benefits over the default implementation:  
- It makes it easier to prevent port exhaustion in for example larger scale provisioning scenarios
- It is faster
- You can take advantage of all the other benefits that comes with HttpClient
Usage example:
``` csharp
var authManager = new PnP.Framework.AuthenticationManager(clientId, certificate, tenantId);
var clientContext = authManager.GetContext(siteUrl);
clientContext.WebRequestExecutorFactory = new …
```

Added implementation of SPWebRequestExecutor that utilizes HttpClient

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs

As this Function already contains the logic we only need to change from int.MaxValue to 511 in order to have Description length limited. 
PnPHttpUtility.ConvertSimpleHtmlToText(parsedGroupDescription, int.MaxValue) 
For the group["notes"] field we can continue to use full size of description.

Fix issue if SP Group has description with more then 512 char

---

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs

- Fixes a "hanging" request that wasn't executed before leaving the method
-Switches from `.Folders.GetByUrl` to `web.GetFolderByServerRelativePath` => interaction with .Folders triggers listview throttling while the other method does, on a big list
Fixes #287 , thanks @patrikhellgren !

[BUGFIX] Hanging request and big list issue with CreateDocumentSet

---

src/lib/PnP.Framework/AuthenticationManager.cs

This PR improves exception messages when acsTokenGenerator is null in AuthenticationManager. This can happen when the AuthenticationManager is created improperly, which can happen easily considering all the possible overloads and different methods, especially when trying to map the old PnP-Sites-Core code.
This PR fixes the following cases:
```c#
// Case 1
var context = new PnP.Framework.AuthenticationManager().GetContext("https://justatest.sharepoint.com");
context.ExecuteQuery();
// Case 2
var token = new PnP.Framework.AuthenticationManager().GetAccessToken("https://justatest.sharepoint.com");
```
With the previous code, this would have triggered a NullReferenceException:
now it will show an error message that explains a bit more in detail what is wrong and what the user should do to …

Improve exception messages when acsTokenGenerator is null in AuthenticationManager

---

src/lib/PnP.Framework/Modernization/Transform/ContentByQuerySearchTransformator.cs

This PR fixes a typo where the result of IEnumerable.Union() is discarded. The author probably assumed this LINQ method was going to modify the collection itself but it actually returns a new collection.
In this particular case the first collection is always empty, so it's enough to just assign the variable to the second collection.
```c#
List<ContentType> cts = new List<ContentType>();
```
Another way could be to assign the result of Union() to the variable `cts` .
Please note that I'm not familiar with how this part of the code is used or how to test it but it looks like a small change only.

Fix IEnumerable.Union() result being discarded in ContentByQuerySearchTransformator

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs

This PR fixes a conversion between PnPCore enum values and PnP.Framework enums. The old code does a C-style cast from the PnPCore enum to the PnP.Framework one but the 2 enums have the possible values defined in different order:
PnPCore:
```c#
//
// Summary:
//     Alignment of the title in a page header
public enum PageHeaderTitleAlignment
{
//
// Summary:
//     Page title is centered
Center,
//
// Summary:
//     Page title is left aligned
Left
}
```
PnP.Framework:
```c#
public enum ClientSidePageHeaderTextAlignment
{
/// <summary>
/// Align Left
/// </summary>
Left,
/// <summary>
/// Align Center
/// </summary>
Center,
}
```
This means PageHeaderTitleAlignment.Left with value 1 gets converted to ClientSidePageHeaderTextAlignment of value 1, so ClientSidePageHeaderTextAlignment.Center …

Fix conversion between PnPCore enum values and PnP.Framework enums

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs

make sure the url to the template document in NewDocumentTemplate-Json is tokenized in export.

Fix tokenize url in new document template

---

src/lib/PnP.Framework/Provisioning/Model/Configuration/ContentTypes/ExtractContentTypeConfiguration.cs
src/lib/PnP.Framework/Provisioning/Model/Configuration/MultiLanguage/ExtractMultiLanguageConfiguration.cs
src/lib/PnP.Framework/Provisioning/Model/Configuration/Navigation/ExtractNavigationConfiguration.cs

Match JsonPropertyName values in ExtractConfiguration with https://aka.ms/sppnp-extract-configuration-schema .
Some properties has different names set in JsonPropertyName that caused the configuration to not be read correctly from json, for example with command
```powershell
Get-PnPSiteTemplate -out test.xml -Configuration config.json
```
To verify which properties had wrong names I serialized ExtractConfiguration to json and validated the result with the schema.
Fix #214

Match JsonPropertyName values in ExtractConfiguration with https://aka.ms/sppnp-extract-configuration-schema

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/FieldUtilities.cs

Fixes #309.
Alternative would be to change `ListExtensions.GetListByUrl` to return `null` when `ServerObjectIsNull == true`, as I assume this issue could occur on other places as well... That would however be more of an impact than wanted I assume. :)
Not sure what's the best approach?

Fix an issue with possible access of null serverobject in FieldUtilities.FixLookupField

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

Fix for token parsing content type names in console and logs. Before this the name would be logged as e.g. {parameter:ContentTypeNameParameter}.

Fix for token parsing content type names in console and logs

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fix for an issue that prevented provisioning of default values for a document library root folder. The setting of default values has support for the root folder by using the folder name "/" but when using that the folder creation process failed so this PR fixes that.

Fix for issue with provisioning default values for root folder

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fix for an issue that appears when trying to provision a template that contains folder default values that are empty, e.g. when using parameters that sometimes has an empty value.

Fix for handling folder default values that are empty in provisioning template

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

Fix:  team site creation issue. Looks like there is some change in the API. Earlier it used to accept LCID value as 0 but now it is more strict and that's why failing. 
Added a check here to skip setting LCID value if it is 0.

Fix:  team site creation issue

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Restore List.EnableFolderCreation value after creating folders, as that action requires this setting to be set to true but is currently never set back to whatever value was set.
Fixes #339

Restore List.EnableFolderCreation value after creating folders

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteSettings.cs

This PR fixes an Access Denied error when processing <pnp:SiteSettings> object caused by ExecuteQuery() calls triggered by helper methods (like site.IsCommunicationSite()) executed on the wrong Context object.
By manually calling ExecuteQuery() right away, we ensure the updated settings are sent using the correct Context object. As many of the helper methods like site.IsCommunicationSite() already trigger ExecuteQuery() calls, it kind of makes the whole `isDirty` pattern useless as it gives the false impression that only 1 call at the end will be made as a single point where the updated settings are sent, while in fact it can happen before too.
This issue fixes https://github.com/pnp/pnpframework/issues/357 , see the long troubleshooting at …

Fix Access Denied error when processing <pnp:SiteSettings> object

---

src/lib/PnP.Framework/PnP.Framework.csproj

Bumped DLL versions for Graph and MSAL.
Had to bump MSAL as it is causing issues with Az modules. 
@ Bert - can you also please update in PnP Core if possible, somehow I couldn't get the build working there on a freshly cloned repo ? 
This PR (https://github.com/pnp/powershell/pull/765) depends on merge of this request and also the one in PnP Core

Feature - Bumped DLL versions

---

src/lib/PnP.Framework/Provisioning/Model/Configuration/Lists/Lists/ExtractListsListsConfiguration.cs

When using the PnP.PowerShell command `Get-PnPSiteTemplate` with a configuration file if you specify the `updateBehavior` property for a list, the entire configuration file is ignored with no error message.
1. Create a config file like this named config.json:
```JSON
{
"$schema":"https://aka.ms/sppnp-extract-configuration-schema",
"handlers": [
"Lists"
],
"lists": {
"lists": [
{
"title": "Bar Graph",
"includeItems": true,
"updateBehavior": "Skip",
"keyColumn": "Title"
}
]
}
}
```
2. Change the title to a list on your site
3. Connect to the site in PnP.PowerShell
4. Run this command
```Terminal
Get-PnPSiteTemplate -Configuration config.json -Out template.xml
```
The entire template will be extracted as if you didn't specify a configuration at all.
When [PnP.PowerShell calls …

Added JsonConvertor decorator to UpdateBehavior

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Fix for an issue that appears when trying to provision a teams tab with a custom app from the app catalog. The app needs to have been added to the team before a tab that references the app can be added.

Fix so that teams apps are added before channels

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/SequenceSiteTokenToken.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenParser.cs

Added a new token called sequencesitetoken to be used to get to specific sequence site tokens in the global template context. This way you can for example use site tokens in Teams channel messages or Teams tabs configurations which was not possible before.
Usage example: ```{sequencesitetoken:MYID:listid:My List}```
I would also like to contribute documentation for this but cannot find anything around the tokens except this one for PnP-SItes-Core which has been archived: [Office 365 Developer PnP Core Component Provisioning Engine Tokens](https://github.com/pnp/PnP-Sites-Core/blob/master/Core/ProvisioningEngineTokens.md). Where should the documentation …

Added new provisioning token for using sequence site tokens in global template context

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Configuration for SharePoint tab was empty. Basically, we have detected an issue trying to use de Website tab with a SharePoint site collection url, it works but all links inside that page loaded from the tab are not working. We have checked that they work if the tab is a SharePoint tab.

Added configuration settings for SharePoint tab entity inside Teams

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs

Add support to ClearExistingItems attribute of <pnp:Members> for custom groups.
Before this PR the attribute ClearExistingItems was checked only for Associated Owners/Members/Visitors group.
https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2021-03.md#userslist is the affected field in the provisioning schema.
Close #243 (even if it was closed already as old)
Close #379
I tested a small template without the field, with the field set to false and with the field set to true and it worked as expected in all 3 cases.
```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.22.2006.2, Culture=neutral, PublicKeyToken=5e633289e95c321a" /> …
```

Add support to ClearExistingItems attribute of <pnp:Members> for custom groups

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

Fix so that the content type UpdateChildren provisioning template property actually is being used when updating content types using PnP provisioning. Before this this was always True.

Fix for content type UpdateChildren not being used

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Now the existing retry code will work as expected. When the CreateOrUpdateTeamFromGroupInternal calls the GraphHelper
```cs
teamId = GraphHelper.CreateOrUpdateGraphObject(.....)
```
If the returned teamId is null or empty, the existing retry code will be hit. The _wait_ variable is set to false only in the teamId is not null
```cs
if (!string.IsNullOrEmpty(teamId))
{
wait = false;
}
```

Issue 390 fixed in CreateOrUpdateTeamFromGroupInternal. 

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

so having for example a & string in field description could break XElement.Parse afterwards.

ProcessFields was using wrong Token-Parser

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/PnPCoreSdk.cs

The way we had the pnpContextCached in PnPCoreSdk we would get potentialy wrong pnpcontext as we cloud have GetClientContext started from User or App Only Context.

Fix pnpcontext cache did not work for multitenant

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Sorry @jansenbe but my previous fix was not good enough, and I detected it can still fail sometimes. Now it also waits 5 seconds between retries in case the TeamId is returned null by the GraphHelper method. I´ve already tested it in my project and is working as expected.
Thanks.

Better fix for issue 390. Now it waits 5 secs between each retry.

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/AssociatedGroupToken.cs

Fix TokenParser always returns original associated-group-names even when renamed by ObjectSiteSecurity.
Since SecurableObjectExtensions will not be able to resolve the old Group-Names the security will not be applied to the objects as they be removed by CheckForAndRemoveNonExistingPrincipals.

Fix TokenParser always returns original associated-group-names

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs

moved searchcenterurl parsing below the commit of pending requests in ObjectWebSettings because the call to web.GetWebSearchCenterUrl(true) makes us otherwise loose the pending settings.

GetWebSearchCenterUrl makes us loose the pending changes in CSOM Context

---

src/lib/PnP.Framework/Graph/UsersUtility.cs

When calling into ListUsers providing additional properties to return using SelectProperties, the results are not getting included in the response. Fixed that with this PR.
Reported through PnP PowerShell [issue 649](https://github.com/pnp/powershell/issues/649).

Including the requested SelectProperties in the output of ListUsers

---

src/lib/PnP.Framework/Extensions/ListExtensions.cs

Fixing issue with SetDefaultColumnValuesImplementation not working for folders with special characters in them
Reported through https://github.com/pnp/powershell/issues/784

Fixing issue with SetDefaultColumnValuesImplementation not working for folders with special characters in them

---

src/lib/PnP.Framework/Extensions/NavigationExtensions.cs

When currently trying to get the footer Title or Image providing a site where the footer is disabled, it will throw a key not found in dictionary exception. This stops `Get-PnPFooter` from working. This PR will fix that issue.

Added additional check to avoid exception when footer not enabled on a site

---

src/lib/PnP.Framework/Http/RetryHandler.cs

Added retry for SocketExceptions in SendAsync to handle e.g. network errors in addition to specific response status codes.

Retry on SocketExcetion in SendAsync

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

There is an issue in the code that is preventing to export properties for files from libraries when there are several content types.
Not sure if affects to more cases. 
In line 587, code is adding ContentTypeId to the pnpFile.Properties. In line 613, was trying to add again the same property key to the dictionary, that was raising an issue.
Changing the way to add properties to the dictionary, it will overwrite it if exists.

Fixing issue when trying to export datarow for list instances

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Hi,
When exporting Team Channels and Tabs, TeamsAppId for the Tab is never retrieved, also, when the Channel Description is null, the Channel description attribute is missing.
Both attributes are required and if they are missing, trying to apply the template, it fails.
There is an opened issue about it.
#444 
I've changed the way that the solution gets the app id to reuse an exiting method that was already in the class. 
This is related with this change
https://github.com/pnp/pnpframework/pull/189
Now, both attributes are provided.

Fix issues exporting channels and tabs with TeamsAppId and Description

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Hi,
Right now, when we are exporting Teams apps, we are getting the Id, that is a base64 encoded string, containing the team id and the app id.
But if we get the XML provided during the export and we try to import it, Graph is claiming about it, we need to use the teamsAppId, that is in the teamAppDefinition object.
See Microsoft doc articles...
https://docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&tabs=http
https://docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&tabs=http

Changed the property we get when exporting Teams apps

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs

Checking taxonomyItem before adding it to the List of terms.
If taxonomyItem was null, it was giving an exception.
#540

Fix for Null Exception when trying to set a term value in a file, listItem, and the term label contains a comma

---

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs
src/lib/PnP.Framework/Sites/SiteCollection.cs

Added Sensitivity Labels to Unified Group Creation

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs

Fix issue in ClientSidePageContentHelper that happens when a container doesn't start with '/'. 
The string.Concat is building the wrong path '{Path_Returned_By_GetContainer}{container}' instead of '{Path_Returned_By_GetContainer}/{container}'.
Using Path combine we avoid that issue
For instance... you can see how that part of the code creates that wrong path {Guid}SiteAssets instead of {Guid}/SiteAssets

Fix issue when folderpath doesn't start by '/'

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

Fix for an exception that occurs while provisioning if using .NET 6 and CurrentCulture is set to a non-standard one e.g. en-SE or en-BE. For more info see [.NET misreports current culture after upgrading to .NET6](https://github.com/dotnet/runtime/issues/60296)

Fix for Culture is not supported exception

---

src/lib/PnP.Framework/PnPCoreSdk.cs

when GetClientContext is called with a PnPContext in order to not reauthenticate when clone context

set ContextSettings Type to ClientContextType.PnPCoreSdk 

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteFooterSettings.cs

Changes:
- Call LocalizeNavigationNode for each child node in footer. Old version only handles localization on each top node.

Added localization support for child nodes in footer

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs

The previously made changes for fix #498 were missing changes required for provisioning the header information.
Additional changes:
* Removed case for `HeaderLayoutType.Standard` in `ExtractObjects`,  because `default` already handles this.
* Removed `scope` variable, because it is not used.
* Removed the `Emphasis` type reference from `Enum.TryParse`, because  the `out` variable already specifies the type.
* `ProvisionObjects` now exits as soon as possible if no changes are required.
* This also moves a possible server call for loading the web URL to a state, were this information would be required.
* Introduced some (single) blank lines to increase the readability of the code.

Additional changes for fix #498

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs

Exporting a client side page with a thumbnail page containing a GUID in the URL is failing if it's not a SP Url.
Catching the exception to continue with the export. 
Related with this issue
#568

Catching File.NotFound exception to prevent error during export

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenParser.cs

Add null check before foreach.
When there are no storage entities created ( for instance at site collection app catalog level ) it was failing.

Check for null before foreach to avoid nullExceptionIssue

---

src/lib/PnP.Framework/Extensions/FieldAndContentTypeExtensions.cs
src/lib/PnP.Framework/Extensions/ListExtensions.cs

Clear-PnPDefaultColumnValues currently throws a NullDereferenceException when invoked on taxonomy fields.
This PR fixes the exception caused by `GetDefaultColumnValueFromField()` returning null when an empty array is passed as argument (meaning "no default taxonomy values"), returning instead a `DefaultColumnTermValue` object with no terms in it,  and changes `SetDefaultColumnValuesImplementation` to clear any default column value if there are none left to be kept.
In addition to this I added a null check in ListExtensions.ClearDefaultColumnValues() as it was triggering a null exception when the folder "Forms" was not present (I didn't investigate further if this happens only in special cases, like modern lists just provisioned).
Fixes https://github.com/pnp/powershell/issues/1110 , …

Fix Clear-PnPDefaultColumnValues not working with taxonomy fields

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

I've modified the class ObjectListInstanceDataRow to allow exporting folder default values.
The PnP Provisioning Schema was already supporting that information but during the extract of a template was not being obtained.
https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2020-02.md#defaultcolumnvalues
That way when getting the site template, we have the nodes pnp:DefaultColumnValues with that information.

Support export folder default values

---

src/lib/PnP.Framework/Graph/GraphUtility.cs
src/lib/PnP.Framework/Graph/UsersUtility.cs

Adding optional useBeta flag into the Microsoft Graph based User functions to allow requesting the beta endpoint at Microsoft Graph to be used. This is i.e. mandatory when wanting to pull in the preferredDataLocation of a user.

Adding beta option to MS Graph Users functions

---

src/lib/PnP.Framework/Graph/UsersUtility.cs

The get user delta did not work well if you were requesting specific properties using the select. It only would return the basic properties, leaving out the additional ones you would have specified. I've updated the entire logic to match the one when not using the delta option. This ensures the output of the two will be similar and they can be used in a mixed fashion. It can be seen as a backwards compatible bugfix.

Rewrite of the get user delta

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

The issue comes with new way of storing spfx config in HostedAppConfigs Field CanvasControl1 - since all data is in attributes the FieldValueAsText strips off all html and leaves a empty string which was skiped. This did result in a weird behavior as  old entries were still exported since there the instance id was still in html as text and therefore not empty but new ones were missed.

fix ProcessDataRow ignore html fields as empty even they are not

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

The target list was retrieved with `GetByTitle` instead of retrieve it with `GetListByUrl`.
This behavior causes errors for native lists (like **Events**) whose title is translated according to the language of the site (**Événements** in French).
Fix #606

Retrieve the target list by url for handler ObjectListInstanceDataRows

---

src/lib/PnP.Framework/Modernization/Pages/PageLayout.cs
src/lib/PnP.Framework/Modernization/Pages/PublishingPage.cs
src/lib/PnP.Framework/Modernization/Publishing/PublishingLayoutTransformator.cs
src/lib/PnP.Framework/Modernization/Publishing/PublishingPageTransformator.cs

Added the possibility to define the exact two column page layout for publishing pages. Now supporting two columns with sidebar right or left.
Also fixed a bug where max columns was set to 0 when web part zones were empty.

Transformation: added specific page layout transformation

---

src/lib/PnP.Framework/Extensions/TenantExtensions.cs

Added method `GetSitePropertiesById` to TenantExtensions which allows for retrieving site collection information based on the site collection Id. Will be used by `Get-PnPTenantSite -Identity <guid>`

Added GetSitePropertiesById functionality to TenantExtensions

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

Currently when a document library has enable moderation activated and has approved folders, when exporting them and provisioning a new site from the template the folders keep pending.
Since there is no attribute on the PnP Schema to set that on the Folder, I've done a change to get _ModerationStatus as property only for Folders ( if it's set in the ViewFields export list configuration ) and also to support modify that field if present during the creation of the folder.

Exporting/Provisioning _ModerationStatus for folders

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs

Issue came with Field MediaServiceImageTags which was already tokenized as {termsetid:System:Image Tags} on a Tenant with the new editable Image Tags feature rolled-out.

do not try to tokenize non Guid termsetids as they probaly already tokenized from List before files

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Issue description: when using resources / localization in folder names (we are creating sites in different languages) setting default field values will not work as tokens are not parsed in folder names.
This PR adds token parsing in folder names before setting default filed values.

Adding token parsing of folder name before setting default field values

---

src/lib/PnP.Framework/AuthenticationManager.cs

While migrating a daemon app I'm facing a deadlock on AcquireTokenForClient method, trying to retrive CSOM ClientContext.
Adding ConfigureAwait(false) solves the problem.

Add ConfigureAwait(false) to AcquireTokenForClient

---

src/lib/PnP.Framework/Diagnostics/PnPMonitoredScope.cs

This PR fixes an issue which occurred when passing a PnPMonitoredScope as a parameter to an async method and then trying to use that passed scope to log messages. Since PnPMonitoredScope was using an internal ThreadStatic variable the async method could not access that variable if switching threads when doing some async work. Making the variable AsyncLocal instead should accomplish somewhat the same thing but making it usable with async work while still creating a new TopScope if used in different threads outside of the same async code flow.

Fix for using passed PnPMonitoredScope in async method

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

This PR changes so that a caught exception during provisioning is not re-thrown which would cause the stack trace to be reset and it was much harder to troubleshoot where the exception originally occurred.

Change to not re-throw caught exception during provisioning

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

The last couple of weeks or so we have started seeing timeouts in PnP Framework teams handler and lots of errors about the team not being found within up to a few minutes of being created. This PR increases some timeouts and adds retry handling to some additional teams api requests and after this everything seems to be running smoothly again.
When implementing retry handling I also refactored the code to start moving away from the dependency on Microsoft.Graph as talked about in #660.

Extend timeouts and add retries to teams provisioning

---

src/lib/PnP.Framework/Extensions/FileFolderExtensions.cs

Improved folder creation a bit by reducing usage of `ExecuteQuery` where possible.
Basically, listUrl and Title field will only be fetched once instead of inside the foreach loop.
We didnt need ensureproperty for folder server relative url, it is always available
Mentioned here : https://github.com/pnp/powershell/issues/1637

Feature: Improve folder creation in EnsureFolderPath method

---

src/lib/PnP.Framework/Provisioning/Providers/Xml/XmlPnPSchemaBaseSerializer.cs

There is a bug in the template provisioning for hierarchy templates. When there is no "ProvisioningTemplate" then it still added a "pnp:Templates". And this will give a invalid xml error
Solution:
Check if there are any "ProvisioningTemplate"

Fix for empty PnP:Templates in the xml

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

If you use application premissions for extracting the teams photo then you will get an error from the Graph Api as the background call in the Graph Api has a bug that it can't be Accessed by "Application" permissions.
Solution:
Add a back-up call to the group photo instead of the teams photo if the teams photo call fails.

Fix for bug with getting the teams photo when using application permissions

---

src/lib/PnP.Framework/PnPCoreSdk.cs

When i use the "await PnPCoreSdk.Instance.GetPnPContextAsync" with a clientcontext with as example the following url: "https://cosmos.sharepoint.com/sites/cosmos". Then the function returns a PnPContext with the sharepoint admin url ("https://cosmos-admin.sharepoint.com/").
Steps to reproduce
Create a client context with a site url.
Use the clientcontext to create a pnpcontext with the following function: "await PnPCoreSdk.Instance.GetPnPContextAsync"
2: try it with clientcontext.Web.Context
Create a client context with a site url.
Use the clientcontext.Web.Context to create a pnpcontext with the following function: "await PnPCoreSdk.Instance.GetPnPContextAsync(web.Context as ClientContext)"
Expected behavior
Expected behavior is a copy of the clientcontext to pnpcontext.
Environment …

Fixed bug with not correct PnPContext from ClientContext

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/FileUniqueIdToken.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/FileUniqueIdTokenEncoded.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs

Fix fileuniqueidencoded, fileuniqueid, pageuniqueidencoded and pageuniqueid export, this can be seen when exporting an hero webpart, the images are missing due to failed replacement. I was updating the template manually when I noticed I could use tokens, as that is cumbersome, I just looked at the code and did this quick fix, so this will work in a future release. The example for fileuniqueid and fileuniqueidencoded was also wrong, the / is trimmed away like for pageuniqueid.

Fix fileuniqueid and pageuniqueid export

---

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs

If there is no member defined in your template then it wil throw a object null error.
Fix :
Check if the member array isn't null

Added null check for checking if members array is not null

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/FieldAndListProvisioningStepHelper.cs

Calculated field should be created after other fields, as with lookup column, to avoid the error "The formula refers to a column that does not exist"

Calculated field should be created after other fields

---

src/lib/PnP.Framework/Extensions/ListExtensions.cs

Issue: Method ClearDefaultColumnValues is failing on exception "The attempted operation is prohibited because it exceeds the list view threshold.", if the list has more than 5000 items.
Fix: Using method GetFormsFolderFromList for loading Forms folder

Fix - ClearDefaultColumnValues in ListExtensions

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectField.cs

Fixes an issue reported on the PnP-Sites-Core repository ([here](https://github.com/pnp/PnP-Sites-Core/issues/2081) 
Reapplying a template containing a list with a calculated field throws  the exception "The formula refers to a column that does not exist. Check the formula for spelling mistakes or change the non-existing column to an existing column."

Fix - Calculated field formula based on title instead of internal name

---

src/lib/PnP.Framework/PnPCoreSdk.cs

I have a scenario where I already have 1) a `ClientContext` and 2) an existing `IPnPContextFactory` with configured PnPCore settings, and I need a `PnPContext` created from that.
Currently there is a `GetPnPContext(Async)` method that allows to create a `PnPContext` from an existing `ClientContext`. But this uses an internal `IPnPContextFactory` that is not configured to use the settings I need. Thus I'd like to pass my own factory.
This pull request makes it possible to pass an already configured factory to be used for `PnPContext` creation.

Allowing to create PnPContext from ClientContext with existing IPnPContextFactory

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Add support to exporting renamed Title columns to a PnP template by not excluding the field when generating a template.
The Title will be included as a FieldRef like below
```xml
<pnp:FieldRefs>
<pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" DisplayName="Renamed title" />
</pnp:FieldRefs>
```
The field changes are already applied by the provisioning engine so no changes are required there.
I have found some old discussions about this change with different opinions. I hope it will be considered as a good addition.

Add support to exporting renamed Title columns to a PnP template

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

A fix for a Bad Request error that occurs when creating private channels. This issue was introduced with the introduction of channel moderation settings since these are not supported for private channels.

Fix for creating private channels

---

src/lib/PnP.Framework/Modernization/Transform/TokenParser.cs

The current implementation only escapes property values containing "$0" and will not escape other Regex $ expressions (e.g. "$", "$1", "$2").
These unescaped Regex $ expressions will be replaced with the whole match value and cause an infinite loop.
Doing property.Value.Replace("$", "$$") ensures all $ chars are properly escaped from the property value.
E.g.
property.Value = _"with a market value estimated to be worth **$** 50 billion by 2025"_ will be replaced by _"with a market value estimated to be worth **with a market value estimated to be worth **$** 50 billion by 2025** 50 billion by 2025"_

Fix for infinite loop in Replacing Tokens when property values contain the Regex special char "$"

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/TokenDefinitions/LocalizationToken.cs

fallback to old logic as for me _defaultLCID has always a Value i.e. 0 or the correct LCID and will throw a error when defaultEntry is null because of the way resources are loaded. You can see first 2 have only one ResourceEntries in specific language and last one has 2 Entries. In case of a EN Default site the second LocalizationToken would fail to load - therefore the fallback.

fix LocalizationToken.GetReplaceValue: fallback to old logic

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs

Failed to resolve termsetid token because IsSiteCollectionGroup was not initialized. 
This is kind of strange since the code was not changed. Therefore, it would think it needs to be a change in CSOM or Backend which leads to that issue.

Fix: Failed to resolve termsetid token

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fix ViewTypeKind property being ignored by SPO when provisioning a new view and updating ListViewXml property during the same ExecuteQueryRetry() call. All views would have ViewType set to HTML before.
The code in this PR first creates the view, calls ExecuteQueryRetry(), then updates the ListViewXml property, then calls ExecuteQueryRetry(). This seems to be needed by serverside behavior of SPO, as ViewCreationInformation is filled with the same information in both cases.
The test was done with a view created from SPO List Settings with "Datasheet View" as base view and then exported with Get-PnPSiteTemplate. The xml template has these attributes:
```xml
<View Name="{221F9B40-A0A0-40AE-9AF6-8C109AD3C6B0}" Type="GRID" Personal="TRUE" DisplayName="Grid view" …
```

Fix ViewTypeKind property being ignored when provisioning views

---

src/lib/PnP.Framework/Utilities/MailUtility.cs

Requested through https://github.com/pnp/powershell/issues/2677

Added optionally providing BCC addresses to send a mail

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Cast TaxonoxyField with appropriate method from web context.
With classic cast, the following exception can be raised: 
`Unable to cast object of type 'Microsoft.SharePoint.Client.Field' to type 'Microsoft.SharePoint.Client.Taxonomy.TaxonomyField'.`
Fix:  #830

Cast TaxonoxyField with appropriate method from web context

---

src/lib/PnP.Framework/Utilities/UrlUtility.cs

Returning back the character ' because since it's valid for URLs, a later call to SharePoint _api/SP.Directory.DirectorySession/Group(alias=....) is failing

Returning character ' as invalid

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Skip setting DefaultColumnValues if there are none specified in the provisioning template.
This avoids adding an unused "LocationBasedMetadataDefaultsReceiver ItemAdded" event receiver (that is currently causing issues on some tenants).

Skip setting DefaultColumnValues if there are none specified in the provisioning template

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Multiple default values for folder were not supported. We have added code to support them for the provisioning.

Adding code to support multiple default values at folder level.

---

src/lib/PnP.Framework/Extensions/SearchExtensions.cs

Allowing a predefined tenant admin URL to be passed in for vanity domain tenants
Reported as an issue through https://github.com/pnp/powershell/issues/2613

Adding support for vanity domain tenants to SearchExtensions

---

src/lib/PnP.Framework.Modernization.Test/PnP.Framework.Modernization.Test.csproj
src/lib/PnP.Framework.Test/PnP.Framework.Test.csproj
src/lib/PnP.Framework/Modernization/Publishing/PublishingBuiltIn.cs
src/lib/PnP.Framework/PnP.Framework.csproj

Bumped the necessary dependencies
and removed these 2 
```
Microsoft.Data.OData
Microsoft.CodeAnalysis.FxCopAnalyzers
```
Working on bumping Graph as well in a separate branch
AppInsights and NewtonSoft versions are the same as that used in PowerShell 7.2.x

Feature: bump dependencies for PnP PowerShell 2.x

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs

Set webpart title and description properties when creating a page that contains webparts. Having a webpart with different preconfigured entries, when adding it manually from the UI, it was setting properly the title to the webpart. 
However, when adding the same webpart in a ClientSidePage with PnP, the title set into the webpart was the title of the main configuration of the webpart, not the preconfigured one....
First control was the one created during the provisioning of the page, the second one, was the added manually.
After the change, both will be the same.

Set Webpart Title and Description during page creation

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Basically in the export of site to a PnP template the content types that were hidden at list level were not coming in the template with the attribute Hidden=True. So the fix is to support this, so if there is a content type not visible at list level if will be returned in the template with Hidden=True

Adding support for content types hidden in the export at list level.

---

src/lib/PnP.Framework/Extensions/ListExtensions.cs

Currently, when the "modern audience targeting" fields are added using PnP the display names are not localized. 
When the fields are added using the SharePoint UI, however, they are.
This PR fixed that by adding the correct Resource-Ids as the display names.

Added localization for modern audience fields.

---

src/lib/PnP.Framework/Sites/SiteCollection.cs
src/lib/PnP.Framework/Sites/SiteCollectionCreationInformation.cs

The Sharepoint REST API supports setting the TimeZoneId and now PnP does too
EDIT: This issue seems related #511

Added support for setting TimeZoneId when creating a new site collection

---

src/lib/PnP.Framework/Provisioning/Providers/Json/JsonTemplateProvider.cs
src/lib/PnP.Framework/Provisioning/Providers/Markdown/MarkdownTemplateProvider.cs
src/lib/PnP.Framework/Provisioning/Providers/TemplateProviderBase.cs
src/lib/PnP.Framework/Provisioning/Providers/Xml/XMLTemplateProvider.cs

Added options to load a tenant template based on a stream and an XML string, like we already had for the site templates. Will be used by PnP PowerShell.

Added Stream and XML option to load Tenant template

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

This fixes a bug in the provisioning engine where default folder values would crash for any field type other than metadata.

fix(provisioning): non-taxonomy default folder values cause error

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

Removing the accents and unallowed characters.
This is necessary for communication and team no-group site collection creation process.
Fixes : https://github.com/pnp/powershell/issues/1190

Feature: improve communication and team nogroup site collection creation

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

Escape apostrophe (single quotes) in alias before calling DirectorySession/Group method. 
For instance, when the alias is something like "What's new", it should be escaped to "What''s new".
This fixes issue #932

Escape apostrophe in alias before calling DirectorySession/Group method

---

docs/contributing/readme.md

fix "}"->"]" in markdown link syntax

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/Utilities/TermGroupHelper.cs

Fixing IsAvailableForTagging not being set correctly on a reused term. It would always use the default of being true, even though the XML import would define it needing to be false. This fixes that it will apply whatever is configured in the XML.

Fixing IsAvailableForTagging not being set correctly on a reused term

---

docs/api/PnP.Framework.Graph.UsersUtility.yml
src/lib/PnP.Framework/Graph/UsersUtility.cs

This PR adds a new method called ListDeletedUsers to UsersUtility class.
It returns a list of deleted users from the tenant.
Underneath, it uses MS Graph [List deletedItems](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http) endpoint to fetch the information.
Method returns a list of Model,User objects.

Add ListDeletedUsers method to UsersUtility

---

src/lib/PnP.Framework/PnP.Framework.csproj

Old System.IdentityModel.Tokens.Jwt 6.27.0 is vulnerable and Visual studio does not allow to build it.

Bump System.IdentityModel.Tokens.Jwt to 6.35.0

---

src/lib/PnP.Framework/Modernization/Extensions/WebExtensions.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePageContents.cs

breaking the page library detection logic
This is the same change, as in https://github.com/pnp/pnpcore/commit/0ea1c82c04342754a64881f5c6b01f8ba579efbf
fixes #974

(#947) Viva Announcement Library resulted in two pages libraries

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

When using `Invoke-PnPTenantTemplate` to create a new Team when using an application context using a clientId and certificate, the group would be created first, then teamified and then permissions would be added on the group for the owners and members. This would fail in an application context as teamifying a group requires an owner to be present first, which is not allowed to be the service principal, before doing so. In this PR we move the part of setting the owners and members from after group creation and teamification to after group creation but before teamification. This fixes this issue. Works well for both delegated as well as application contexts now.

Fixing issue apply TenantTemplate creating a new Team in an application context

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs
src/lib/PnP.Framework/Extensions/TenantExtensions.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/PnPProvisioningContext.cs
src/lib/PnP.Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
src/lib/PnP.Framework/Sites/SiteCollection.cs
src/lib/PnP.Framework/Utilities/Context/ClientContextType.cs
src/lib/PnP.Framework/Utilities/Context/ManagedIdentityType.cs

Adding Managed Identity support for PnP Framework means i.e. you can now use PnP tenant provisioning within a managed identity structure

Adding Managed Identity support to PnP Framework

---

src/lib/PnP.Framework/AuthenticationManager.cs

On on-premise environments, it happens that the GetUpdatedFormDigestInformation is invoked multiple times causing multiple digest values in the X-RequestDigest header. This in turn causes SharePoint to throw 403: forbidden responses.
This small change fixes this issue.
Closes #1010

fix(auth): fix issue in ConfigureOnPremisesContext causing 403 forbidden responses on on-premise environments

---

src/lib/PnP.Framework/ALM/AppManager.cs

When getting app metadata after an app has been added, if  `metadataResponse.StatusCode == HttpStatusCode.NotFound` then it will retry the request but without creating a new HttpRequestMessage. This causes the following error "System.InvalidOperation: The request was already sent. Cannot send the same request multiple times".  
In this fix I included the creation of the HttpRequestMessage inside the while loop so that each time a retry is made, it creates a new HttpRequestMessage.

Fix "The request was already sent" error when getting app metadata (using AppManager)

---

src/lib/PnP.Framework/Extensions/WebExtensions.cs

Should fix #1015 
In the past, the method was working fine with just setting an Empty value in the ```RequestAccessEmail```. However, this is not working anymore (I tested it in 2 different tenants).
Now it needs an extra step first calling ```SetUseAccessRequestDefaultAndUpdate(false)```

fixing issue #1015

---

src/lib/PnP.Framework/AuthenticationManager.cs

Repro steps (F#):
let am=new AuthenticationManager()
let ctx=am.GetACSAppOnlyContext("https://contoso.sharepoint.com/sites/mysite", clientId, clientSecret)
//..................................
let cs=ctx.GetContextSettings()
let t=cs.AuthenticationManager.GetAccessToken("https://contoso.sharepoint.com/sites/mysite")

we should specify Uri, otherwise it will throw NRE

---

src/lib/PnP.Framework/Graph/UnifiedGroupsUtility.cs
src/lib/PnP.Framework/Sites/SiteCollection.cs

Feature: improve Group creation by adding support for additional parameters for SharePoint sites

Feature: improve Group creation by adding support for additional parameters for SharePoint sites

---

src/lib/PnP.Framework/AuthenticationManager.cs

Updating UsGovernment (ie GCC) URL endpoints to be correct.  GCC uses mostly Azure Commercial, not Azure Government.  The endpoints in this PR have been updated to be correct while leaving UsGovernmentHigh (ie GCC High) and UsGovernmentDoD unchanged.

Update AuthenticationManager.cs for GCC (ie UsGovernment) Regions

---

src/lib/PnP.Framework/AuthenticationManager.cs

Updating UsGovernment enum for SharePoint domain suffix to be .com vs previous .us.

Update AuthenticationManager.cs for GCC SharePoint suffix value

---

src/lib/PnP.Framework/AuthenticationManager.cs
src/lib/PnP.Framework/Utilities/Cache/MsalCacheHelperUtility.cs

Improve authentication performance by caching on file system

Feature: Improve authentication performance by caching on file system

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs

The original fix was expecting the PageTitle WebPart to be the first in the first section which needs to be a OneColumnFullWith.
#1058
#1043
It seems that this assumption was wrong and it can be in any section. The check has been changed to reflect this.
This fix is related to the pnp.core fix https://github.com/pnp/pnpcore/pull/1543.

Fix check for HeaderTypes as new PageTitle WebPart in OneColumnFullWIth is not always in first section

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
src/lib/PnP.Framework/Provisioning/Providers/Xml/PnPObjectsMapper.cs

Fix #1075 by improving handling custom sort order by checking for empty values.
Also fixes a typo in someone else's comment - sorry, it caught my eye :)

Improves handling taxonomy custom sort order by checking for empty values

---

src/lib/PnP.Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

General channel is not created by default anymore.
Now Teams allows to define the first Channel name when creating the Teams.
Initialize the first channel found.

General channel is not created by default anymore, check first channel when creating and initialize Teams

---

src/lib/PnP.Framework/Sites/SiteCollection.cs

Handle urls ending with / when creating new sites by removing any empty entry after splitting the url by /.
This is needed when the url ends with / as the last part after `Split('/')` will just be an empty string, causing `Replace("", "")` to be called, throwing an exception.
This has been reported at https://github.com/pnp/powershell/issues/4491 and can be reproduced calling New-PnPSite:
```powershell
New-PnPSite -Type TeamSiteWithoutMicrosoft365Group -Owner <owner upn> -Url "https://<tenant>.sharepoint.com/sites/TestWithSlash/" -Title "Test With Slash"
```
The PR fixes the issue and the site is created:

Handle urls ending with / when creating new sites

---

src/lib/PnP.Framework/Extensions/ListExtensions.cs

Replacing hard coded user information list value with instance that should resolve regardless of the language of the site

Replacing hard coded user information list value with instance that should resolve regardless of the language of the site

---

src/lib/PnP.Framework/Extensions/TenantExtensions.cs

Adding support for vanity domains for GetHubSiteChildUrls. See #1012 for a similar change.
Tested with a local build of PnP PowerShell with command **Get-PnPHubSiteChild**.

Adding tenantAdminUrl parameter for GetHubSiteChildUrls

---

src/lib/PnP.Framework/Diagnostics/TraceLogger.cs

Warnings were being logged as informational instead of warnings. Fixing that here.

Fixing logging of warnings as informational

---

src/lib/PnP.Framework/Http/HttpClientWebRequestExecutorFactory.cs

Allowing the response-type header to be missing to avoid unclear exceptions. Concrete scenario is when connecting using a Client Secret and doing any basic stuff, such as fetching properties of say a Web, it will throw an exception that the token type (client secret) is not allowed. This response does not have a Content-Type header. This causes a generic exception to be thrown which is far from clear:
The situation over the wire when this happens is as follows:
With this fix, at least it gives some indication that the issue is with authorization:
I could not get my hands on the actual super clear JSON response to pass with the exception, which would even be nicer, as that seems encapsulated within the native CSOM assembly.

Allowing the response-type header to be missing
